-- Apex shares table
--
-- Stores share/challenge tokens generated by the iOS app. Each row backs a
-- short URL of the form https://apexvert.com/v/<token> or /c/<token>.
--
-- `payload` schema (kept loose as JSONB for forward compatibility):
--   {
--     "name":           string,            -- display name (or initials only)
--     "initials":       string,
--     "vertMeters":     number,
--     "label":          string,            -- "ELITE" | "ATHLETIC" | ...
--     "color":          "blue" | "green" | "orange" | "red",
--     "jumpType":       "running" | "standing",
--     "dateISO":        string | null,     -- omitted if user hides date
--     "includesPhoto":  boolean,
--     "photoUrl":       string | null      -- only set if user opted in
--   }
--
-- Tokens are 6-char base62 strings generated client-side and verified server-
-- side for collisions before insert.

create table if not exists shares (
  token                       text primary key,
  kind                        text not null check (kind in ('vert', 'challenge')),
  payload                     jsonb not null,
  created_at                  timestamptz not null default now(),
  view_count                  integer not null default 0,
  install_attributed_count    integer not null default 0
);

create index if not exists shares_created_at_idx on shares (created_at desc);
create index if not exists shares_kind_idx on shares (kind);

-- Helpful for cleanup later (e.g. drop shares older than N months that nobody opened)
create index if not exists shares_view_count_idx on shares (view_count);
